### ISSUE TITLE
Shared data source example not working

### ISSUE THREAD

**Issue by Myles12345** [sgratzl/lineup_htmlwidget#2]
Was just trying the example on this vignette for the using with lineup with crosstalk. 

```
devtools::install_github("rstudio/crosstalk")
devtools::install_github("sgratzl/lineup_htmlwidget")
library(lineup)




devtools::install_github("jcheng5/d3scatter")
library(d3scatter)

shared_iris = SharedData$new(iris)

d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species, width="100%")
lineup(shared_iris, width="100%")
```
I'm not getting an error - but within the viewer in RStudio - I'm just getting a **blank screen**.    

I notice this alternate version works, albeit **without** the crosstalk functionality:
 
`devtools::install_github("Caleydo/lineup_htmlwidget")`

Has crosstalk functionality been abandoned?

This looks like a really useful tool - especially linked with crosstalk - I really like where you are going with this!

**Comment by sgratzl** [comment]
please note the warning it the README.md file: 

> It can be used within standalone R Shiny apps or R Markdown files. *Integrated plotting does not work due to an outdated integrated Webkit version in RStudio*. Crosstalk is supported for synching selections and filtering among widgets.

**Comment by Myles12345** [comment]
Sorry - it says very clearly and works wonderfully using flexdashboard.   Thank you for the clarification and sorry to waste your time.

**Comment by sgratzl** [comment]
no big deal, have fun with the library. if you encounter bugs, feel free to file an issue
